### ISSUE TITLE
line 80: division by zero

### ISSUE THREAD

**Issue by toedtli** [maxnoe/python-plotting#2]
In line 80, there's a "1/3" which python evaluates as 0, yielding a division by zero. It should be "1/3.".

**Comment by MaxNoe** [comment]
I use python 3.

**Comment by MaxNoe** [comment]
Also: which file exactly?

**Comment by toedtli** [comment]
Ok, I understand. The file was
python-plotting/source/create_pi_labels.py
Lines 20 and 82
